### ISSUE TITLE
Alterações

### ISSUE THREAD

**Issue by gabrielbarretosc** [KienKse/analisadorCod#2]
Além de alterar o nome da variavel para regexFuncao, alterar o que o regex deverá achar:
Pude constatar que começam as funções em: 

int void boolean static hresult ulong const ntstatus

não sei se: 

**Quickie** e **TryAgain** deverão ser considerados como funções.

Não testei:
private static final String regexFunction = ".*(int|void|boolean|static|hresult|ulong|const|ntstatus(.*\\)";

**Comment by gabrielbarretosc** [comment]
C só possuem funções, constantes, tipos definidos, macros e variáveis globais (ainda que raro, porque é desaconselhável).

Contar como uma classe cada vez que sair do arquivo e ir para o outro?

**Comment by gabrielbarretosc** [comment]
Metodo: listFile
Em: FolderReader

if (arquivo.getName().contains(".java"))

alterar para: ".c"

**Comment by KienKse** [comment]
> Metodo: listFile
> Em: FolderReader
> 
> if (arquivo.getName().contains(".java"))
> 
> alterar para: ".c"

Não me diga...

**Comment by KienKse** [comment]
> Além de alterar o nome da variavel para regexFuncao, alterar o que o regex deverá achar:
> Pude constatar que começam as funções em:
> 
> int void boolean static hresult ulong const ntstatus
> 
> não sei se:
> 
> **Quickie** e **TryAgain** deverão ser considerados como funções.
> 
> Não testei:
> private static final String regexFunction = "._(int|void|boolean|static|hresult|ulong|const|ntstatus(._\)";

regex não funciona

**Comment by KienKse** [comment]
(static|void|int|List|int|Integer|double|Double|String|string|char|long|Long|boolean|float).*([A-z]|main).*[(].*([A-z]|void|.*)

to verify on site:
(static|void|int|List|int|Integer|double|Double|String|string|char|long|Long|boolean|float).*([A-z]|main).*[(].*([A-z]|void|.*)\n{
